/**
 * Pre-build script for package client files.
 * Transpiles client/*.ts → client/dist/*.js and generates a manifest.
 *
 * Run before publishing: deno task build:client
 */

import { getEsbuild } from "./esbuildInit.ts";
import type { Loader } from "esbuild";

type ClientSourceEntry = {
  file: Deno.DirEntry;
  logicalName: string;
  loader: Loader;
  sourceCode: string;
};

async function computeBuildHash(
  packageVersion: string,
  entries: ClientSourceEntry[],
): Promise<string> {
  const hashInput = [
    packageVersion,
    ...entries.flatMap((
      { logicalName, sourceCode },
    ) => [logicalName, sourceCode]),
  ].join("\n\0\n");
  const digest = await crypto.subtle.digest(
    "SHA-256",
    new TextEncoder().encode(hashInput),
  );

  return Array.from(new Uint8Array(digest))
    .map((value) => value.toString(16).padStart(2, "0"))
    .join("")
    .slice(0, 8);
}

async function writeTextFileIfChanged(
  path: string,
  content: string,
): Promise<boolean> {
  const existingContent = await Deno.readTextFile(path).catch(() => null);
  if (existingContent === content) {
    return false;
  }

  await Deno.writeTextFile(path, content);
  return true;
}

export async function buildPackageClientFiles(): Promise<void> {
  const clientDir = `${import.meta.dirname}/client`;
  const distDir = `${clientDir}/dist`;

  const packageConfig = JSON.parse(
    await Deno.readTextFile(new URL("./deno.json", import.meta.url)),
  ) as { version?: string };
  const packageVersion = typeof packageConfig.version === "string"
    ? packageConfig.version
    : "0.0.0";
  const normalizedVersion = packageVersion.replace(/[^a-zA-Z0-9.-]/g, "-");

  await Deno.mkdir(distDir, { recursive: true });

  const files = (await Array.fromAsync(Deno.readDir(clientDir)))
    .filter((entry) => entry.isFile)
    .filter((entry) =>
      entry.name.endsWith(".ts") || entry.name.endsWith(".tsx")
    );

  console.log(`Transpiling ${files.length} client files → client/dist/`);

  const sourceEntries = await Promise.all(files.map(async (file) => ({
    file,
    logicalName: file.name.replace(/\.(ts|tsx)$/i, ".js"),
    loader: (file.name.toLowerCase().endsWith(".tsx") ? "tsx" : "ts") as Loader,
    sourceCode: await Deno.readTextFile(`${clientDir}/${file.name}`),
  })));

  sourceEntries.sort((left, right) =>
    left.logicalName.localeCompare(right.logicalName)
  );

  const buildHash = await computeBuildHash(packageVersion, sourceEntries);

  const manifestEntries = sourceEntries.map((entry) => ({
    ...entry,
    outName: entry.logicalName.replace(
      /\.js$/i,
      `.v${normalizedVersion}.${buildHash}.js`,
    ),
  }));

  const manifest = Object.fromEntries(
    manifestEntries.map(({ logicalName, outName }) => [logicalName, outName]),
  ) as Record<string, string>;

  for (const { file, outName, loader, sourceCode } of manifestEntries) {
    const esbuild = await getEsbuild();
    const result = await esbuild.transform(sourceCode, {
      loader,
      format: "esm",
      target: ["esnext"],
      sourcemap: false,
    });

    const outputCode = result.code.replace(
      /(from\s+["'])([^"']+)(\.tsx?)(["'])/g,
      "$1$2.js$4",
    ).replace(
      /(from\s+["'])(\.\/[^"']+\.js)(["'])/g,
      (_match: string, prefix: string, importPath: string, suffix: string) => {
        const importedLogicalName = importPath.slice(2);
        const importedBuiltName = manifest[importedLogicalName];

        if (!importedBuiltName) {
          return `${prefix}${importPath}${suffix}`;
        }

        return `${prefix}./${importedBuiltName}${suffix}`;
      },
    );

    const updated = await writeTextFileIfChanged(
      `${distDir}/${outName}`,
      outputCode,
    );
    console.log(
      updated
        ? `  ${file.name} → dist/${outName}`
        : `  ${file.name} unchanged (dist/${outName})`,
    );
  }

  const generatedFiles = new Set(manifestEntries.map(({ outName }) => outName));
  for await (const entry of Deno.readDir(distDir)) {
    if (
      entry.isFile &&
      entry.name.endsWith(".js") &&
      !generatedFiles.has(entry.name)
    ) {
      await Deno.remove(`${distDir}/${entry.name}`);
      console.log(`  removed stale dist/${entry.name}`);
    }
  }

  const manifestCode = [
    "// Auto-generated by buildClientFiles.ts — do not edit",
    `export const packageVersion = ${JSON.stringify(packageVersion)} as const;`,
    `export const buildHash = ${JSON.stringify(buildHash)} as const;`,
    `export const clientFileManifest = ${
      JSON.stringify(manifest, null, 2)
    } as const;`,
    "export type ClientFile = keyof typeof clientFileManifest;",
    "export const clientFiles = Object.values(clientFileManifest) as readonly string[];",
    "export function getClientFileName(file: ClientFile): string {",
    "  return clientFileManifest[file];",
    "}",
    "",
  ].join("\n");
  const manifestUpdated = await writeTextFileIfChanged(
    `${distDir}/manifest.ts`,
    manifestCode,
  );
  console.log(
    manifestUpdated
      ? `  manifest.ts (${manifestEntries.length} files)`
      : `  manifest.ts unchanged (${manifestEntries.length} files)`,
  );

  const esbuild = await getEsbuild();
  esbuild.stop();
  console.log("Done.");
}

if (import.meta.main) {
  await buildPackageClientFiles();
}
