/**
 * Pre-build script for package client files.
 * Transpiles client/*.ts → client/dist/*.js and generates a manifest.
 *
 * Run before publishing: deno task build:client
 */

import * as esbuild from "esbuild";

const clientDir = `${import.meta.dirname}/client`;
const distDir = `${clientDir}/dist`;

await Deno.mkdir(distDir, { recursive: true });

const files = (await Array.fromAsync(Deno.readDir(clientDir)))
  .filter((entry) => entry.isFile)
  .filter((entry) => entry.name.endsWith(".ts") || entry.name.endsWith(".tsx"));

console.log(`Transpiling ${files.length} client files → client/dist/`);

const manifest: string[] = [];

for (const file of files) {
  const inputCode = await Deno.readTextFile(`${clientDir}/${file.name}`);
  const loader = file.name.toLowerCase().endsWith(".tsx") ? "tsx" : "ts";
  const result = await esbuild.transform(inputCode, {
    loader,
    format: "esm",
    target: ["esnext"],
    sourcemap: false,
  });

  // Convert .ts/.tsx imports to .js
  const outputCode = result.code.replace(
    /(from\s+["'])([^"']+)(\.tsx?)(["'])/g,
    "$1$2.js$4",
  );

  const outName = file.name.replace(/\.(ts|tsx)$/i, ".js");
  await Deno.writeTextFile(`${distDir}/${outName}`, outputCode);
  manifest.push(outName);
  console.log(`  ${file.name} → dist/${outName}`);
}

// Write manifest as a TS module so build.ts can import it
const manifestCode =
  `// Auto-generated by buildClientFiles.ts — do not edit\nexport const clientFiles = ${
    JSON.stringify(manifest.sort(), null, 2)
  } as const;\n`;
await Deno.writeTextFile(`${distDir}/manifest.ts`, manifestCode);
console.log(`  manifest.ts (${manifest.length} files)`);

esbuild.stop();
console.log("Done.");
