/**
 * Pre-build script for package client files.
 * Transpiles client/*.ts → client/dist/*.js and generates a manifest.
 *
 * Run before publishing: deno task build:client
 */

import * as esbuild from "esbuild";

const clientDir = `${import.meta.dirname}/client`;
const distDir = `${clientDir}/dist`;

const packageConfig = JSON.parse(
  await Deno.readTextFile(new URL("./deno.json", import.meta.url)),
) as { version?: string };
const packageVersion = typeof packageConfig.version === "string"
  ? packageConfig.version
  : "0.0.0";
const normalizedVersion = packageVersion.replace(/[^a-zA-Z0-9.-]/g, "-");
const buildHash = crypto.randomUUID().replace(/-/g, "").slice(0, 8);

await Deno.mkdir(distDir, { recursive: true });

const files = (await Array.fromAsync(Deno.readDir(clientDir)))
  .filter((entry) => entry.isFile)
  .filter((entry) => entry.name.endsWith(".ts") || entry.name.endsWith(".tsx"));

console.log(`Transpiling ${files.length} client files → client/dist/`);

const manifestEntries = files.map((file) => {
  const logicalName = file.name.replace(/\.(ts|tsx)$/i, ".js");
  const outName = logicalName.replace(
    /\.js$/i,
    `.v${normalizedVersion}.${buildHash}.js`,
  );

  return {
    file,
    logicalName,
    outName,
    loader: file.name.toLowerCase().endsWith(".tsx") ? "tsx" : "ts",
  };
}).sort((left, right) => left.logicalName.localeCompare(right.logicalName));

const manifest = Object.fromEntries(
  manifestEntries.map(({ logicalName, outName }) => [logicalName, outName]),
) as Record<string, string>;

for (const { file, outName, loader } of manifestEntries) {
  const inputCode = await Deno.readTextFile(`${clientDir}/${file.name}`);
  const result = await esbuild.transform(inputCode, {
    loader,
    format: "esm",
    target: ["esnext"],
    sourcemap: false,
  });

  // Convert .ts/.tsx imports to .js
  const outputCode = result.code.replace(
    /(from\s+["'])([^"']+)(\.tsx?)(["'])/g,
    "$1$2.js$4",
  ).replace(
    /(from\s+["'])(\.\/[^"']+\.js)(["'])/g,
    (_match, prefix: string, importPath: string, suffix: string) => {
      const importedLogicalName = importPath.slice(2);
      const importedBuiltName = manifest[importedLogicalName];

      if (!importedBuiltName) {
        return `${prefix}${importPath}${suffix}`;
      }

      return `${prefix}./${importedBuiltName}${suffix}`;
    },
  );

  await Deno.writeTextFile(`${distDir}/${outName}`, outputCode);
  console.log(`  ${file.name} → dist/${outName}`);
}

const generatedFiles = new Set(manifestEntries.map(({ outName }) => outName));
for await (const entry of Deno.readDir(distDir)) {
  if (
    entry.isFile &&
    entry.name.endsWith(".js") &&
    !generatedFiles.has(entry.name)
  ) {
    await Deno.remove(`${distDir}/${entry.name}`);
    console.log(`  removed stale dist/${entry.name}`);
  }
}

// Write manifest as a TS module so build.ts can import it
const manifestCode = [
  "// Auto-generated by buildClientFiles.ts — do not edit",
  `export const packageVersion = ${JSON.stringify(packageVersion)} as const;`,
  `export const buildHash = ${JSON.stringify(buildHash)} as const;`,
  `export const clientFileManifest = ${
    JSON.stringify(manifest, null, 2)
  } as const;`,
  "export type ClientFile = keyof typeof clientFileManifest;",
  "export const clientFiles = Object.values(clientFileManifest) as readonly string[];",
  "export function getClientFileName(file: ClientFile): string {",
  "  return clientFileManifest[file];",
  "}",
  "",
].join("\n");
await Deno.writeTextFile(`${distDir}/manifest.ts`, manifestCode);
console.log(`  manifest.ts (${manifestEntries.length} files)`);

esbuild.stop();
console.log("Done.");
